steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sgm-modcidadao", "."]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/sgm-modcidadao"]
  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/sgm-modcidado-k', 'my-container=gcr.io/$PROJECT_ID/sgm-modcidadao']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sgm-modcidadao-cluster1'        
images:
  - "gcr.io/$PROJECT_ID/sgm-modcidadao"